### ISSUE TITLE
ReplCommentConnection

### ISSUE THREAD

**Issue by rayhanadev** [Coding-Cactus/repltalk#1]
Hiya! Just a small tip for your package, did you know you can fetch a Repl project's comments?

```js
query Repl($id: Int!) {
  replById(id: $id) {
    comments(count: 1000000) { 
      ...on Repl {
        pageInfo { 
          nextCursor 
        } 
        items { 
          // The Comment Fields...
        } 
      }
    }
  }
}
```

**Comment by Coding-Cactus** [comment]
I would assume you could. This gem is nowhere near done, I'm still working through basic Client methods, so just give me time lol

**Comment by rayhanadev** [comment]
Of course, I just remembered it :)

**Comment by Coding-Cactus** [comment]
Hi @RayhanADev  thank you for your suggestion, I think I have added it here: https://github.com/Coding-Cactus/repltalk/commit/3682bd2cbeed1c1d00478c2e4155cb7c5a3e9b25 

If you have any more suggestions, please let me know!
